/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    ComparisonCardUI: typeof import('./src/components/chat/ComparisonCardUI.vue')['default']
    ConfidenceDot: typeof import('./src/components/chat/ConfidenceDot.vue')['default']
    ConfirmationCard: typeof import('./src/components/ConfirmationCard.vue')['default']
    ConfirmationCardUI: typeof import('./src/components/chat/ConfirmationCardUI.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    ConversationList: typeof import('./src/components/chat/ConversationList.vue')['default']
    CostFooter: typeof import('./src/components/chat/CostFooter.vue')['default']
    GenericChildTable: typeof import('./src/components/chat/GenericChildTable.vue')['default']
    ItemMappingTable: typeof import('./src/components/chat/ItemMappingTable.vue')['default']
    MessageBubble: typeof import('./src/components/chat/MessageBubble.vue')['default']
    NewConversationDialog: typeof import('./src/components/chat/NewConversationDialog.vue')['default']
    PdfPreview: typeof import('./src/components/chat/PdfPreview.vue')['default']
    ProgressBanner: typeof import('./src/components/chat/ProgressBanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaxMappingTable: typeof import('./src/components/chat/TaxMappingTable.vue')['default']
    ThinkingIndicator: typeof import('./src/components/chat/ThinkingIndicator.vue')['default']
    UndoBanner: typeof import('./src/components/chat/UndoBanner.vue')['default']
    UpdateCardUI: typeof import('./src/components/chat/UpdateCardUI.vue')['default']
  }
}
