/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComparisonTable: typeof import('./src/components/ComparisonTable.vue')['default']
    ConfirmationCard: typeof import('./src/components/ConfirmationCard.vue')['default']
    DocumentThumbnail: typeof import('./src/components/DocumentThumbnail.vue')['default']
    ExtractionForm: typeof import('./src/components/ExtractionForm.vue')['default']
    ExtractionPreview: typeof import('./src/components/ExtractionPreview.vue')['default']
    FileDropzone: typeof import('./src/components/FileDropzone.vue')['default']
    MissingMastersDialog: typeof import('./src/components/MissingMastersDialog.vue')['default']
    ProcessingStatus: typeof import('./src/components/ProcessingStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
  }
}
